version: '3.9'

services:
  mysql_order_service:
    image: mysql:8.0-debian
    container_name: mysql_order-service
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
    volumes:
      - data-mysql-order-service:/var/lib/mysql
    restart: always
    networks:
      - microservices_network


volumes:
  data-mysql-order-service:

networks:
  microservices_network:
    driver: bridge